-- =========================================================
-- Single Image to 3D Reconstruction
-- User Authentication & History Schema
-- Version: 1.0.0
-- =========================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================================================
-- PROFILES
-- =========================================================

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_email_unique ON public.profiles(email);

COMMENT ON TABLE public.profiles IS 'Application user profiles synced with auth.users.';
COMMENT ON COLUMN public.profiles.id IS 'Primary key referencing auth.users.id.';
COMMENT ON COLUMN public.profiles.email IS 'User email address.';
COMMENT ON COLUMN public.profiles.last_login IS 'Timestamp of the user''s last authenticated sign-in.';

-- =========================================================
-- JOBS
-- =========================================================

CREATE TABLE IF NOT EXISTS public.jobs (
    job_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,
    original_filename TEXT NOT NULL,
    original_image_url TEXT,
    thumbnail_url TEXT,
    status TEXT NOT NULL
        CHECK (
            status IN (
                'uploaded',
                'processing',
                'completed',
                'failed'
            )
        ),
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    processing_duration_seconds DOUBLE PRECISION
        CHECK (
            processing_duration_seconds IS NULL
            OR processing_duration_seconds >= 0
        ),
    model_generated BOOLEAN NOT NULL DEFAULT FALSE,
    pointcloud_generated BOOLEAN NOT NULL DEFAULT FALSE,
    pipeline_version VARCHAR(20) NOT NULL DEFAULT '2.0.0',
    error_message TEXT,
    processing_device TEXT,
    gpu_name TEXT,
    input_width INTEGER,
    input_height INTEGER,
    total_pipeline_time_ms BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_jobs_user
ON public.jobs(user_id);

CREATE INDEX IF NOT EXISTS idx_jobs_created
ON public.jobs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_jobs_status
ON public.jobs(status);

CREATE INDEX IF NOT EXISTS idx_jobs_user_status_created
ON public.jobs(user_id, status, created_at DESC);

COMMENT ON TABLE public.jobs IS 'Reconstruction pipeline execution jobs.';
COMMENT ON COLUMN public.jobs.job_id IS 'Unique identifier for the reconstruction job.';
COMMENT ON COLUMN public.jobs.processing_duration_seconds IS 'Inference execution duration in seconds.';

-- =========================================================
-- ARTIFACTS
-- =========================================================

CREATE TABLE IF NOT EXISTS public.artifacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id UUID NOT NULL
        REFERENCES public.jobs(job_id)
        ON DELETE CASCADE,
    artifact_type TEXT NOT NULL
        CHECK (
            artifact_type IN (
                'original',
                'enhanced',
                'detection',
                'part_detection',
                'mask',
                'segmentation',
                'mask_overlay',
                'rgba',
                'model',
                'pointcloud',
                'segmented_pointcloud',
                'caption',
                'grounding_prompt',
                'result'
            )
        ),
    storage_path TEXT NOT NULL,
    file_size BIGINT,
    mime_type VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(job_id, artifact_type)
);

CREATE INDEX IF NOT EXISTS idx_artifacts_job
ON public.artifacts(job_id);

COMMENT ON TABLE public.artifacts IS 'Metadata tracking for files generated by the pipeline.';

-- =========================================================
-- ENABLE RLS
-- =========================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles FORCE ROW LEVEL SECURITY;

ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs FORCE ROW LEVEL SECURITY;

ALTER TABLE public.artifacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artifacts FORCE ROW LEVEL SECURITY;

-- =========================================================
-- PROFILES POLICIES
-- =========================================================

DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile"
ON public.profiles
FOR SELECT
USING (
    auth.uid() = id
);

DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile"
ON public.profiles
FOR UPDATE
USING (
    auth.uid() = id
)
WITH CHECK (
    auth.uid() = id
);

-- =========================================================
-- JOBS POLICIES
-- =========================================================

DROP POLICY IF EXISTS "Users can view own jobs" ON public.jobs;
CREATE POLICY "Users can view own jobs"
ON public.jobs
FOR SELECT
USING (
    auth.uid() = user_id
    AND is_deleted = FALSE
);

DROP POLICY IF EXISTS "Users can insert own jobs" ON public.jobs;
CREATE POLICY "Users can insert own jobs"
ON public.jobs
FOR INSERT
WITH CHECK (
    auth.uid() = user_id
);

DROP POLICY IF EXISTS "Users can update own jobs" ON public.jobs;
CREATE POLICY "Users can update own jobs"
ON public.jobs
FOR UPDATE
USING (
    auth.uid() = user_id
)
WITH CHECK (
    auth.uid() = user_id
);

DROP POLICY IF EXISTS "Users can delete own jobs" ON public.jobs;
CREATE POLICY "Users can delete own jobs"
ON public.jobs
FOR DELETE
USING (
    auth.uid() = user_id
);

-- =========================================================
-- ARTIFACTS POLICIES
-- =========================================================

DROP POLICY IF EXISTS "Users can view own artifacts" ON public.artifacts;
CREATE POLICY "Users can view own artifacts"
ON public.artifacts
FOR SELECT
USING (
    EXISTS (
        SELECT 1
        FROM public.jobs
        WHERE
            jobs.job_id = artifacts.job_id
            AND jobs.user_id = auth.uid()
            AND jobs.is_deleted = FALSE
    )
);

DROP POLICY IF EXISTS "Users can insert own artifacts" ON public.artifacts;
CREATE POLICY "Users can insert own artifacts"
ON public.artifacts
FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.jobs
        WHERE
            jobs.job_id = artifacts.job_id
            AND jobs.user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Users can update own artifacts" ON public.artifacts;
CREATE POLICY "Users can update own artifacts"
ON public.artifacts
FOR UPDATE
USING (
    EXISTS (
        SELECT 1
        FROM public.jobs
        WHERE
            jobs.job_id = artifacts.job_id
            AND jobs.user_id = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.jobs
        WHERE
            jobs.job_id = artifacts.job_id
            AND jobs.user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Users can delete own artifacts" ON public.artifacts;
CREATE POLICY "Users can delete own artifacts"
ON public.artifacts
FOR DELETE
USING (
    EXISTS (
        SELECT 1
        FROM public.jobs
        WHERE
            jobs.job_id = artifacts.job_id
            AND jobs.user_id = auth.uid()
    )
);

-- =========================================================
-- UPDATED_AT TRIGGER
-- =========================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
CREATE TRIGGER update_profiles_updated_at
BEFORE UPDATE
ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_jobs_updated_at ON public.jobs;
CREATE TRIGGER update_jobs_updated_at
BEFORE UPDATE
ON public.jobs
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- =========================================================
-- AUTO CREATE PROFILE
-- =========================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO public.profiles (
        id,
        email,
        created_at,
        updated_at,
        last_login
    )
    VALUES (
        NEW.id,
        NEW.email,
        NOW(),
        NOW(),
        NEW.last_sign_in_at
    )
    ON CONFLICT (id)
    DO UPDATE
    SET
        email = EXCLUDED.email,
        updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT
ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();

-- =========================================================
-- UPDATE LAST LOGIN
-- =========================================================

CREATE OR REPLACE FUNCTION public.handle_user_login()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE public.profiles
    SET
        last_login = NEW.last_sign_in_at,
        updated_at = NOW()
    WHERE id = NEW.id;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_login ON auth.users;
CREATE TRIGGER on_auth_user_login
AFTER UPDATE OF last_sign_in_at
ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_user_login();

-- =========================================================
-- END OF MIGRATION
-- =========================================================
